### PR TITLE
Gallery slider

### PR DESCRIPTION
**Pull request by demshy**

### CODE REVIEW

**Comment by salamca** [comment]
Image displayed in slide (fullsize) is smaller than it is displayed in a grid. 
example: Krabi, dum's kitchen:

actual image size is 238x600:
image


grid:
image


full:
image

**Comment by salamca** [comment]
Clicking in white space around image and then sliding keeps displaying blue outline square:

image

**Comment by salamca** [comment]
Double clicking a 'small' image resizes it to larger than full. I suggest we also constrain the size on fullscreen view to max of image's intrinsic size; that is never enlarge the image. 

Esc on fullscreen returns to grid. I would suggest only exiting fulscreen (then if another esc pressed return to grid).

Sliding does not work in fullscren (although arrow press does switch images with some delay). 

Could add rounded borders on slider (not fullscreen) view.

Not sure about cursor:pointer on the image and around it. maybe cursor:default?

**Comment by salamca** [comment]
can we disable image selection on slider to prevent this:
image

**Comment by demshy** [comment]
all comments have been addressed

**Review by salamca — APPROVED** [review]

**Pull request merged**
