### PR TITLE
TextArea component

### PR DESCRIPTION
**Pull request by NejcS**
This adds the `TextArea` component and its sandbox page. I copied a lot of the code over from `TextInput` since they both use the same React Aria hook but with different parameters. There is some code duplication but I think it's better to have the two components separated since they don't also have the same props (prefix and suffix vs. rows) and there is not that much code anyway.

image

### CODE REVIEW

**Comment by salamca** [comment]
Margin between label and input should be larger (8px)
image


I think invalid+focus needs another type of styling. 
I missed this one and will add to Figma, check in couple of mins... :)
Will also add a fix to the still opened https://github.com/plezanje-net/next-web/pull/16

**Comment by NejcS** [comment]
> I think invalid+focus needs another type of styling.

Maybe this is ok for invalid + focused:
image

User clicks submit > form gets invalidated > input gets red outline and error message > user clicks on input and it gets the "focused" outline.

**Comment by salamca** [comment]
> > I think invalid+focus needs another type of styling.
> 
> Maybe this is ok for invalid + focused: image
> 
> User clicks submit > form gets invalidated > input gets red outline and error message > user clicks on input and it gets the "focused" outline.

this is the way.
(no special logic really, I just think it looks nicer this way. :) )

image

you can merge https://github.com/plezanje-net/next-web/tree/various-ui-components-fixes to get the colour, and might just copy logic from text-field

**Comment by salamca** [comment]
There is a slight blue border behind the red border on invalid focused:
image

I am guessing that the style is applied to the inner textarea html element instead of to the outer div.



Both the prefilled and invalid usecases are not editable, but probably should be.

**Pull request merged**
